spring:
  application.name: rabbitmq.producer.two
  rabbitmq:
    addresses: localhost:5672
    username: admin
    password: admin123
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true

